package asm8

import (
	"io"
)

type Gen interface {
	Decl(b *Builder, block interface{})
	Build(b *Builder, block interface{})
	Obj() interface{}
}

// Builder manipulates an AST, checks its syntax, and builds the assembly
type Builder struct {
	p    *Parser
	errs *ErrList

	Gen Gen
}

func newBuilder(file string, r io.ReadCloser) *Builder {
	ret := new(Builder)
	ret.p = NewParser(file, r)
	ret.errs = NewErrList()

	return ret
}

// Build builds the blocks generated by the parser.
func (b *Builder) Build() (interface{}, []*Error) {
	var blocks []interface{}

	for {
		block := b.p.Block()
		if block == nil {
			break
		}
		blocks = append(blocks, block)
	}

	errs := b.p.Errs()
	if errs != nil {
		return nil, errs
	}

	if b.Gen == nil {
		return int(0), nil
	}

	// declare the blocks, register the symbols
	for _, block := range blocks {
		b.Gen.Decl(b, block)
	}

	// build the blocks, generate the context
	for _, block := range blocks {
		b.Gen.Build(b, block)
	}

	if b.errs.Errs != nil {
		return nil, b.errs.Errs
	}

	return b.Gen.Obj(), nil
}
